version: '3'
services:
  db:
    build: db
    environment:
      POSTGRES_USER: "tardisbank_app"
      POSTGRES_PASSWORD: "_wHaT3v3R"
      POSTGRES_DB: "tardisbank"
    ports: 
      - "5432:5432"
      
  api:
    build: server
    environment:
      TARDISBANK_DB_CON: "Server=db;Port=5432;Database=tardisbank;User Id=tardisbank_app;Password=_wHaT3v3R;"
    ports:
      - "5000:5000"
      
  client:
    build: client
    ports:
      - "3000:3000"