version: "3"
services:
  db:
    container_name: tardis_bank_db
    build: ./db
    environment:
      POSTGRES_USER: ${TARDISBANK_DB_USER:-tardisbank_app}
      POSTGRES_PASSWORD: ${TARDISBANK_DB_PASSWORD:-password}
      POSTGRES_DB: ${TARDISBANK_DB_DATABASENAME:-tardisbank}
    expose:
      - "5432"

  api:
    container_name: tardis_bank_api
    image: tardisbank/server
    environment:
      TARDISBANK_DB_CON: "Server=db;Port=5432;Database=${TARDISBANK_DB_DATABASENAME:-tardisbank};User Id=${TARDISBANK_DB_USER:-tardisbank_app};Password=${TARDISBANK_DB_PASSWORD:-password};"
      TARDISBANK_KEY: ${TARDISBANK_KEY:-secret-key}
      TARDISBANK_SMTP_SERVER: "mail:25:false"
      TARDISBANK_SMTP_CREDENTIALS: "${TARDISBANK_SMTP_CREDENTIALS:-username@example.com:password}"
      ASPNETCORE_ENVIRONMENT: "development"
    expose:
      - "80"
    depends_on:
      - db

  nginx:
    container_name: tardis_bank_nginx
    image: tardisbank/nginx
    volumes:
      - static-content:/usr/share/nginx/html
    depends_on:
      - api
      - client

  client:
    container_name: tardis_bank_static
    image: tardisbank/client
    environment:
      UUNODE_ENV: prod
    volumes:
      - static-content:/app/build

volumes:
  static-content:
