name: continuous integratation
on: [push]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: set envs
        run: |
          echo "::set-env name=BUILD_VERSION::$(git describe --tags)"
          echo "$BUILD_VERSION"

      - name: Get github slug variables
        uses: rlespinasse/github-slug-action@master

      - name: run deploy script
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          DOT_ENV: ${{ secrets.DOT_ENV }}
          COMPOSE_PROJECT_NAME: ${{ env.GITHUB_REF_SLUG }}
        run: |
          eval $(ssh-agent -s)

          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          ssh-keyscan $REMOTE_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          echo "${DOT_ENV}" > ./devops/.env
          echo "COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}" >> ./devops/.env

          chmod u+x ./devops/deploy.sh
          ./devops/deploy.sh
